--------------------------------------------------------
--  File created - Sexta-feira-Dezembro-16-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LEILAO
--------------------------------------------------------

  CREATE TABLE "BD"."LEILAO" 
   (	"ID" NUMBER, 
	"CLIENTNAME" VARCHAR2(20 BYTE), 
	"MAXAMOUNT" NUMBER, 
	"MINBIDID" NUMBER, 
	"TITLE" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"DEADLINE" DATE, 
	"ITEM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into BD.LEILAO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index LEILAO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD"."LEILAO_PK" ON "BD"."LEILAO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table LEILAO
--------------------------------------------------------

  ALTER TABLE "BD"."LEILAO" ADD CONSTRAINT "LEILAO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BD"."LEILAO" MODIFY ("MAXAMOUNT" NOT NULL ENABLE);
  ALTER TABLE "BD"."LEILAO" MODIFY ("CLIENTNAME" NOT NULL ENABLE);
  ALTER TABLE "BD"."LEILAO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table LEILAO
--------------------------------------------------------

  ALTER TABLE "BD"."LEILAO" ADD CONSTRAINT "FK_BID_LEILAO" FOREIGN KEY ("MINBIDID")
	  REFERENCES "BD"."BID" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "BD"."LEILAO" ADD CONSTRAINT "FK_CLIENTE_LEILAO" FOREIGN KEY ("CLIENTNAME")
	  REFERENCES "BD"."CLIENTE" ("NOME") ON DELETE CASCADE ENABLE;
