--------------------------------------------------------
--  File created - Sexta-feira-Dezembro-16-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MESSAGE
--------------------------------------------------------

  CREATE TABLE "BD"."MESSAGE" 
   (	"ID" NUMBER, 
	"CLIENTNAME" VARCHAR2(20 BYTE), 
	"TEXT" VARCHAR2(255 BYTE), 
	"LEILAOID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into BD.MESSAGE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index MESSAGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD"."MESSAGE_PK" ON "BD"."MESSAGE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MESSAGE
--------------------------------------------------------

  ALTER TABLE "BD"."MESSAGE" ADD CONSTRAINT "MESSAGE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BD"."MESSAGE" MODIFY ("LEILAOID" NOT NULL ENABLE);
  ALTER TABLE "BD"."MESSAGE" MODIFY ("CLIENTNAME" NOT NULL ENABLE);
  ALTER TABLE "BD"."MESSAGE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table MESSAGE
--------------------------------------------------------

  ALTER TABLE "BD"."MESSAGE" ADD CONSTRAINT "FK_CLIENTE_MESSAGE" FOREIGN KEY ("CLIENTNAME")
	  REFERENCES "BD"."CLIENTE" ("NOME") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BD"."MESSAGE" ADD CONSTRAINT "FK_LEILAO_MESSAGE" FOREIGN KEY ("LEILAOID")
	  REFERENCES "BD"."LEILAO" ("ID") ON DELETE CASCADE ENABLE;
