--------------------------------------------------------
--  File created - Sexta-feira-Dezembro-16-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table NOTIFICATION
--------------------------------------------------------

  CREATE TABLE "BD"."NOTIFICATION" 
   (	"ID" NUMBER, 
	"CLIENTNAME" VARCHAR2(20 BYTE), 
	"TEXT" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"CLIENTENVIOU" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into BD.NOTIFICATION
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index NOTIFICATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD"."NOTIFICATION_PK" ON "BD"."NOTIFICATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table NOTIFICATION
--------------------------------------------------------

  ALTER TABLE "BD"."NOTIFICATION" ADD CONSTRAINT "NOTIFICATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BD"."NOTIFICATION" MODIFY ("CLIENTNAME" NOT NULL ENABLE);
  ALTER TABLE "BD"."NOTIFICATION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table NOTIFICATION
--------------------------------------------------------

  ALTER TABLE "BD"."NOTIFICATION" ADD CONSTRAINT "FK_CLIENTE_NOTIFICATION" FOREIGN KEY ("CLIENTNAME")
	  REFERENCES "BD"."CLIENTE" ("NOME") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BD"."NOTIFICATION" ADD CONSTRAINT "FK_CLIENTE_NOTIFICATION_2" FOREIGN KEY ("CLIENTENVIOU")
	  REFERENCES "BD"."CLIENTE" ("NOME") ON DELETE CASCADE ENABLE;
